"""Create Table Produto

Revision ID: f02ab2f93bc5
Revises: 
Create Date: 2024-08-23 08:15:19.951537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f02ab2f93bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_produto', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_produto', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
